server:
  port: 9201

spring:
  application:
    name: carbon-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Đã thêm &allowPublicKeyRetrieval=true vào cuối dòng dưới đây
    url: jdbc:mysql://localhost:3306/carbon_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B7&allowPublicKeyRetrieval=true
    username: root
    password: root # <--- NHẬP MẬT KHẨU MYSQL CỦA BẠN VÀO ĐÂY
